# Generated by Django 4.2.4 on 2023-09-29 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_categoria_seccion_delete_categoriaprod_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='genero',
            field=models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer'), ('X', 'Unisex')], default='X', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='talla',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], max_length=4, null=True),
        ),
    ]
