# Generated by Django 4.2.4 on 2023-09-29 22:22

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_alter_producto_talla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='genero',
            field=models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer'), ('X', 'Unisex')], default='X', max_length=1),
        ),
        migrations.AlterField(
            model_name='producto',
            name='talla',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], max_length=5, null=True),
        ),
    ]
