# Generated by Django 4.2.4 on 2023-09-29 22:23

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_alter_producto_genero_alter_producto_talla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='talla',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], max_length=8, null=True),
        ),
    ]
