# Generated by Django 4.2.4 on 2023-11-16 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0009_remove_producto_talla_prod_calzado_prod_ropa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prod_Accesorio',
            fields=[
                ('producto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tienda.producto')),
            ],
            options={
                'verbose_name': 'accesorio',
                'verbose_name_plural': 'accesorios',
            },
            bases=('tienda.producto',),
        ),
        migrations.AlterModelOptions(
            name='prod_calzado',
            options={'verbose_name': 'calzado', 'verbose_name_plural': 'calzados'},
        ),
        migrations.AlterModelOptions(
            name='prod_ropa',
            options={'verbose_name': 'ropa', 'verbose_name_plural': 'ropas'},
        ),
    ]
