# Generated by Django 4.2.4 on 2023-11-16 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0010_prod_accesorio_alter_prod_calzado_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'marca',
                'verbose_name_plural': 'marcas',
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(default='Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen', max_length=1500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='tienda.marca'),
            preserve_default=False,
        ),
    ]
