# Generated by Django 4.2.4 on 2023-11-16 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0011_marca_producto_descripcion_producto_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(max_length=1500),
        ),
    ]
