# Generated by Django 4.2.4 on 2023-12-03 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('preparando', 'EN PREPARACION'), ('reparto', 'EN REPARTO'), ('entregado', 'ENTREGADO')], default='PREPARANDO'),
        ),
    ]
