# Generated by Django 4.2.4 on 2023-12-03 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_pedido_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('preparando', 'EN PREPARACION'), ('reparto', 'EN REPARTO'), ('entregado', 'ENTREGADO'), ('cancelado', 'CANCELADO')], default='PREPARANDO'),
        ),
    ]
