# Generated by Django 4.2.4 on 2023-12-06 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_remove_productopedido_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productopedido',
            name='talla',
            field=models.CharField(default='M', max_length=2),
            preserve_default=False,
        ),
    ]
