# Generated by Django 4.2.4 on 2023-12-06 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_productopedido_talla'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productopedido',
            table=None,
        ),
    ]
