# Generated by Django 4.2.4 on 2023-12-07 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0008_remove_direcciones_pedido_pedido_direccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direcciones',
            name='numero',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
