# Generated by Django 4.2.4 on 2023-12-11 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0010_alter_productopedido_talla'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='precioTotal',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
