# Generated by Django 4.2.4 on 2023-12-11 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0011_pedido_preciototal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='precioTotal',
        ),
    ]
