# Generated by Django 4.2.4 on 2023-12-13 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0012_remove_pedido_preciototal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='direcciones',
            options={'ordering': ['id'], 'verbose_name': 'direccion', 'verbose_name_plural': 'direcciones'},
        ),
        migrations.AlterModelTable(
            name='pedido',
            table=None,
        ),
    ]
